# Use the official Node.js 14 image as the base image
FROM alpine:3.18
RUN apk add --no-cache nodejs npm
RUN apk add --update npm
#RUN npm install -g npm@latest
RUN npm install -g react@latest
RUN npm install -g create-react-app@latest
RUN npm install -g react-dom@latest
WORKDIR /app
COPY . /app/
RUN chmod +x /app/startServices.sh
CMD ["/bin/sh", "-c", "/app/startServices.sh"]